// Details transcribed from the original Alternative Service Plan animated diagrams.
window.ASP_DATA = [
  {
    number: "01",
    detail: "Line blockage at station 3A1, track 2.",
    service: "3A1 track 1 to 3K1, both tracks.",
    shuttle: "",
  },
  {
    number: "02",
    detail: "Line blockage at station 3A1, track 1.",
    service: "3B2 PF2 to 3K1.",
    shuttle: "3A1 to 3B1, track 2.",
  },
  {
    number: "03",
    detail: "Line blockage from station 3A1 to 3B1.",
    service: "3B2 to 3K1, both tracks.",
    shuttle: "",
  },
  {
    number: "04",
    detail: "Line blockage at stations 3B2 and 3D3, both tracks.",
    service: "3D1 to 3K1.",
    shuttle: "3A1 to 3B1, both tracks.",
  },
  {
    number: "05",
    detail: "Line blockage at stations 3C2 and 3D3, both tracks.",
    service: "3A1 to 3B2; 3D1 to 3K1.",
    shuttle: "",
  },
  {
    number: "06",
    detail: "Zone controller failure affecting stations 3A1 to 3D3.",
    service: "3D1 to 3K1.",
    shuttle: "",
  },
  {
    number: "07",
    detail: "Passage Post 2 failure affecting stations 3D1 to 3E3.",
    service: "3A1 to 3B2; 3F1 to 3K1.",
    shuttle: "3E4 to 3F1 PF1, both tracks.",
  },
  {
    number: "08",
    detail: "Line blockage at station 3D1, both tracks.",
    service: "3A1 to 3B2; 3E3 PF2 to 3K1.",
    shuttle: "3D2 to 3E3 on track 1; 3D2 to 3E2 on track 2.",
  },
  {
    number: "09",
    detail: "Line blockage from station 3D2 to 3E1, both tracks.",
    service: "3A1 to 3D1; 3E2 to 3K1.",
    shuttle: "",
  },
  {
    number: "10",
    detail: "Line blockage from station 3D2 to 3E3 PF1.",
    service: "3A1 to 3D1; 3E3 to 3K1.",
    shuttle: "",
  },
  {
    number: "11",
    detail: "Line blockage at station 3E3, both tracks.",
    service: "3A1 to 3E2 PF1; 3F1 to 3K1.",
    shuttle: "3E4 to 3E6 on track 1; 3E4 to 3F1 on track 2.",
  },
  {
    number: "12",
    detail: "Zone controller failure affecting stations 3D1 to 3E4.",
    service: "3A1 to 3B2; 3G1 to 3K1.",
    shuttle: "3E5 to 3F2, both tracks.",
  },
  {
    number: "13",
    detail: "Line blockage at stations 3E4, 3E5, and 3E6, both tracks.",
    service: "3A1 to 3E3; 3F1 to 3K1.",
    shuttle: "",
  },
  {
    number: "14",
    detail: "Passage Post 3 failure affecting station 3E5.",
    service: "3A1 to 3E3; 3G1 to 3K1.",
    shuttle: "",
  },
  {
    number: "15",
    detail: "ODS failure at station 3F2, both tracks.",
    service: "3A1 to 3F1; 3G1 to 3K1.",
    shuttle: "",
  },
  {
    number: "16",
    detail: "ODS failure affecting stations 3F2 to 3G1.",
    service: "3A1 to 3F1.",
    shuttle: "",
  },
  {
    number: "17",
    detail: "Line blockage at stations 3F2 and 3G1, both tracks.",
    service: "3A1 to 3F1.",
    shuttle: "3G2 to 3K1, both tracks.",
  },
  {
    number: "18",
    detail: "Line blockage at stations 3F1 and 3F2, both tracks.",
    service: "3A1 to 3E6; 3G1 to 3K1.",
    shuttle: "",
  },
  {
    number: "19",
    detail: "ODS failure affecting stations 3H1 and 3J1.",
    service: "3A1 to 3G1 PF2.",
    shuttle: "",
  },
  {
    number: "20",
    detail: "Line blockage from station 3J1, track 2, to East Depot.",
    service: "3A1 to 3J1 PF1.",
    shuttle: "",
  },
  {
    number: "21",
    detail: "Line blockage at station 3K1, both tracks.",
    service: "3A1 to 3J1.",
    shuttle: "",
  },
  {
    number: "22",
    detail: "Line blockages from station 3A1 to 3K1.",
    service: "Not applicable.",
    shuttle: "Not applicable.",
  },
].map((plan) => ({
  ...plan,
  title: `Alternative Services Mainline ${plan.number}`,
  animation: `asp/asp-${plan.number}.gif`,
  thumbnail: `asp/thumbnails/asp-${plan.number}.webp`,
}));
